baseURL = "https://musved.de"
languageCode = "en-us"
title = "Müsvedde - Adı üstünde"
theme = "PaperMod"
# post pagination
paginate = "10"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disable language
disableLanguages = [""] # desable language from here

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[markup.goldmark.renderer]
    unsafe = true
[markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = false

copyright = "© 2023 -  Ahmet Önder Moğol"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#googleAnalytics = "UA-123-45"
#disqusShortname = "ink-demo"

[params]
	subtitle = "Müsvedde olduğunu düşündüğünüz fikirler değerlidir."

	# Optional 64x64 avatar image.
	#avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/aomogol"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
